version: '3.8'

# All containers
services:
  # db container
  db:
    image: postgres:15
    container_name: aegis-db
    restart: always
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: aegis_db        
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend container
  backend:
    build: .
    container_name: aegis-api  # (builds container using the )
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: